"""add_lat_lng_to_projects

Revision ID: cfc53b8ef4af
Revises: 0011_methodology_regulations
Create Date: 2026-09-29 05:56:36.999961
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'cfc53b8ef4af'
down_revision = '0011_methodology_regulations'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_versions', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('permissions_key_key'), 'permissions', type_='unique')
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=True)
    op.add_column('projects', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'longitude')
    op.drop_column('projects', 'latitude')
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=False)
    op.create_unique_constraint(op.f('permissions_key_key'), 'permissions', ['key'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_versions', 'uploaded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
